
INSERT INTO TESTE VALUES (6,'SEXTO TESTE')
INSERT INTO TESTE VALUES (7,'SETIMO TESTE')
INSERT INTO TESTE VALUES (8,'OITAVO TESTE')
INSERT INTO TESTE VALUES (9,'NOVO TESTE')
INSERT INTO TESTE VALUES (10,'DECIMO TESTE')

